// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ModalsController from "./modals_controller"
application.register("modals", ModalsController)

import SelectController from "./select_controller"
application.register("select", SelectController)

import SelfYeeterController from "./self_yeeter_controller"
application.register("self-yeeter", SelfYeeterController)

import SuggestedRecipesController from "./suggested_recipes_controller"
application.register("suggested-recipes", SuggestedRecipesController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)

import UiLoadingController from "./ui_loading_controller"
application.register("ui-loading", UiLoadingController)
